### ISSUE TITLE
Suggestion: Use $ naming conventions

### ISSUE THREAD

**Issue by Bunkerbewohner** [themagickoala/lexical-remark#2]
Hi!

I was wondering whether it would make sense to use the $ prefix for `createRemarkImport` and `exportLexicalToMarkdown`, since internally they use `$getRoot`, and to signal that they should only be used within methods like the EditorState's `read` or Editor's `update`.

What do you think?

**Comment by themagickoala** [comment]
I think that's probably a good idea. I'll probably do it as a non-breaking change and deprecate the non-prefixed versions.

**Comment by themagickoala** [comment]
Resolved in v0.0.27
